name: build

on: [push, workflow_dispatch]

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate version properties
        run: |
          try
          {
            ./src/VersionInfo.ps1 -Verbose -ErrorAction Stop
          }
          catch
          {
            Write-Warning $_
          }
          
          exit 0

      - name: Run tests
        run: dotnet.exe test .\src\LdifHelper.sln --configuration Release